[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
AgentsPlots = "7820620d-95fb-4739-93b3-b0a14dd83f9a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
